### ISSUE TITLE
Hang when authorizing

### ISSUE THREAD

**Issue by invliD** [mckenfra/postgresql-mac-preferences#3]
Hello,

the preference pane hangs for me when trying to authenticate. I can enter my admin password, but after that, System Preferences freezes and eats 100% of my CPU.
OS: 10.8.3
MacBook Pro Retina 13"

invliD.

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.2?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Unless I hear otherwise from you, I'll assume this issue is fixed so I'll close it soon.

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.4?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Unless I hear otherwise from you, I'll assume this issue is fixed so I'll close it soon.

**Comment by invliD** [comment]
@mckenfra Unfortunately, I cannot test this anymore since my environment has changed.

**Comment by mckenfra** [comment]
OK thanks for the reply. I'll close the issue but feel free to reopen another issue if you see the problem again.
