### ISSUE TITLE
Get initial settings from pg_config

### ISSUE THREAD

**Issue by tkrajacic** [mckenfra/postgresql-mac-preferences#6]
I installed the prefs pane having the homebrew version of postresql installed.
The setting tab shows the default paths which are incorrect for the postgres instance actually running.
This is confusing me. If I stop the server and restart, I would guess that the pref pane would try to launch postgres with the default values and not the homebrew version? Am I right? I am afraid to try ;)
I guess the bin directory "/usr/local/opt/postgresql/bin" belongs to Apple's system-supplied version?

Why not fill out the settings fields with values retrieved from the currently running instance (if there is one) using pg_config? Or have the pane recognize default installation variants.

Also, the "start at boot" checkbox is ticked when I launch the pane. Checking with `launchctl list | grep post` still only shows the launchDaemon installed by homebrew, and it sure doesn't start postgresql at launch as it still sits in ~/Library/LaunchAgents/

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.2?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Unless I hear otherwise from you, I'll assume this issue is fixed so I'll close it soon.

**Comment by tkrajacic** [comment]
Just installed it, and it correctly showed Postgres as running. (I still have the homebrew version installed)
Stopped the server via pane: psql was correctly stopped
Started the server again via pane: psql was started

Excellent work!

Needs fixing: Rename the Text on the checkbox! The Postgres server is NOT started on Startup, but on Login! (You'd have to create a plist in LaunchDaemons and not LaunchAgents for that as I explained earlier)

**Comment by mckenfra** [comment]
Right, I see what you mean now. Yes, this tool creates a `.plist` only in the `LaunchAgents` dir, so it is definitely run-on-login as opposed to run-on-bootup.

Unless people see a specific need for a run-on-bootup option, I'll change the text in the GUI as you suggest. Thanks!

**Comment by tkrajacic** [comment]
It's the easier fix ;)

I think it would be helpful to have "run at boot" if you have a server where you don't wanna be logged in all the time (and you really don't). Almost all tutorials for that give the same wrong instructions not realizing the difference between boot and login startup.

**Comment by mckenfra** [comment]
Yup, that's a good point. There's potentially a use-case for a run-on-boot. I'll pencil that in for a future release!

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.4?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

I made the change to the text in the interface as you suggested. Let me know if you're ok to close this issue.

**Comment by tkrajacic** [comment]
Looks good! You can close the issue I guess.

**Comment by mckenfra** [comment]
Ok thanks
