### ISSUE TITLE
How did it stop the server?

### ISSUE THREAD

**Issue by kevinzzz007** [mckenfra/postgresql-mac-preferences#8]
OMG, this is probably the best thing that happened to me!  I spent over 6 hours trying to find a way to kill my PostgreSQL, but nothing worked. Once I use your program, it worked like a charm!  What command did you use to stop my server?

You are the BEST!  Thank you so so much!

**Comment by mckenfra** [comment]
glad it helped!

You have to use launchctl to start/stop the postgres server. Otherwise if you kill the process it will just automatically restart it I think

**Comment by kevinzzz007** [comment]
Aha, so using pg_ctl stop won't work but launchctl will work because my PostgreSQL started at login?  How do I prevent it from starting at login?

**Comment by mckenfra** [comment]
You need to look in `/Library/LaunchDaemons`, `/Library/LaunchAgents` and `${HOME}/Library/LaunchAgents` for any `.plist` files relating to PostgreSQL. You can either delete those files, or use `/usr/libexec/Plistbuddy` to change the settings in those files that control auto-startup.

This is what I'm working on right at this moment! You could wait for me to finish updating the tool, or you could try doing this manually yourself. Up to you!

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.2?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Let me know if that's working now.

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.4?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Unless I hear back from you soon, I'll close this issue.

**Comment by kevinzzz007** [comment]
Hi there, feel free to close the issue, I will try it once I get back from holidays. Thanks a bunch!

**Comment by mckenfra** [comment]
No probs, thanks!
